pipeline {
      agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: kubectl
    image: bryandollery/terraform-packer-aws-alpine
    command:
    - cat
    tty: true
  - name: helm
    image: alpine/helm
    command:
    - cat
    tty: true
"""
    }
  }
  environment {
    TOKEN=credentials('90aa8adf-f03e-45ea-8ea4-b721a512e53c')
  }

    stages {
      stage("Deploy") {
          steps {
              container('kubectl') {
                  sh '''
		      kubectl --token=$TOKEN  create namespace monitor

                  '''
              }
          }
      }
        stage('helm-deploy') {
	  steps {
                  container('helm') {
                      sh '''
  		helm repo add stable https://kubernetes-charts.storage.googleapis.com
                helm repo update
		helm install prometheus-operator stable/prometheus-operator --namespace monitor --set grafana.service.type=LoadBalancer


		    '''
                    }
            }
        }
    }
}
