pipeline {
      agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    service_name: elk-service
spec:
  containers:
  - name: kubectl
    image: bryandollery/terraform-packer-aws-alpine
    command:
    - cat
    tty: true
  - name: helm
    image: alpine/helm
    command:
    - cat
    tty: true
"""
    }
  }
  environment {
    TOKEN=credentials('465384ac-317b-4932-a35f-3f017dbed2b6')
    SERVICE_NAME = 'elk-service'
  }

    stages {
      stage("Deploy") {
          steps {
              container('kubectl') {
                  sh '''
		      kubectl --token=$TOKEN create namespace elf       
		      '''
              }
          }
      }
     stage('helm-deploy') {
	  steps {
                  container('helm') {
                      sh '''
  			helm repo add elastic https://helm.elastic.co
			helm repo add fluent https://fluent.github.io/helm-charts
			helm repo update
			helm install elasticsearch elastic/elasticsearch --version=7.9.0 --namespace=elf
			helm install fluent-bit fluent/fluent-bit --namespace=elf
			helm install kibana elastic/kibana --version=7.9.0 --namespace=elf --set service.type=NodePort
		    '''
                    }
            }
        }
        stage('apply') {
	  steps {
                  container('kubectl') {
                      sh '''
  			kubectl run random-logger --image=chentex/random-logger -n elf
                     	 cd $SERVICE_NAME
                     	 kubectl --token=$TOKEN apply -f ingress.yaml -n elf
                    
		    '''
                    }
            }
        }
    }
}
