pipeline {
      agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: kubectl
    image: bryandollery/terraform-packer-aws-alpine
    command:
    - cat
    tty: true
  - name: helm
    image: alpine/helm
    command:
    - cat
    tty: true
"""
    }
  }
  environment {
    TOKEN=credentials('4ff0bfed-4fc0-4f54-b80e-3c0569b79790')
  }

   stages {
      stage("init") {
          steps {
                container('kubectl') {
                   sh 'make elf'
              }
          }
      }
        
    }
}
